name: Template Registry Verification

defaults:
  run:
    shell: bash

on:
  schedule:
    - cron: "*/5 * * * *"
  issue_comment:
    types: [created]

jobs:
  create-issue:
    name: Create "Template Registry Verification" Issue
    runs-on: ubuntu-latest
    if: (github.event_name == 'issue_comment' && github.event.comment.body == '/check-registry')
    permissions:
      issues: write
    outputs:
      issue-number: ${{ steps.issue.outputs.issue-number }}
    steps:
      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=today::$(date '+%m/%d/%Y')"
      - name: Create "Template Registry Verification" Issue
        uses: imjohnbo/issue-bot@v3.3.6
        id: issue
        with:
          labels: "verify-template-registry"
          title: '"Template Registry Verification" (${{ steps.date.outputs.today }})'
          body: |
            ### Template Registry Verification
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  get-packages:
    name: Get packages that should be checked
    runs-on: ubuntu-latest
    needs: [create-issue]
    outputs:
      error: ${{ steps.packages.outputs.error }}
      packages: ${{ steps.packages.outputs.list }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Get packages that should be checked
        id: packages
        run: node src/get-packages-for-verification.js
  matrix:
    name: Test matrix
    runs-on: ubuntu-latest
    needs: [get-packages]
    strategy:
      matrix: ${{ fromJSON(needs.get-packages.outputs.packages) }}
    steps:
      - run: |
          echo ${{ matrix.packages }}
  verify-template-registry:
    name: Template Registry Verification
    runs-on: ubuntu-latest
    needs: [create-issue]
    outputs:
      error: ${{ steps.verify-template-registry.outputs.error }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Verify Template Registry
        id: verify-template-registry
        run: node src/verify-template-registry.js ${{ needs.create-issue.outputs.issue-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
